name: conjur-action Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  authn-jwt:
    runs-on: self-hosted
    
    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
      - uses: actions/checkout@v1
      - name: Use CyberArk Conjur Secret Fetcher Action w/ GitHub JWT
        uses: ./
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: conjur
          authn_id: ${{ secrets.CONJUR_SERVICE_ID }}
          secrets: data/edge-test-github-1|sql_username; data/edge-test-github-2|sql_password
      - name: Check SQL_USERNAME Outside Docker Container for Secret Masking
        run: printenv SQL_USERNAME | sed 's/./& /g'
      - name: Check SQL_PASSWORD Outside Docker Container for Secret Masking
        run: printenv SQL_PASSWORD | sed 's/./& /g'


